### PR TITLE
Add parameter "properties" in model "Trace"

### PR DESCRIPTION
**Pull request by siwei-zhang-work**
Add the parameter "properties" introduced by commit 499408e3979cab403a5d58 in the server (incubator).

Link to the PR for the commit: https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/79

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Note: the license check CI workflow is currently failing \[*\] in most of our cdt.cloud repos, on dependency `npm/npmjs/-/electron-to-chromium/1.5.13`.  We believe it's a false-positive.

**Comment by marcdumais-work** [comment]
@bhufmann We are getting that same 3PP license check failure in many of our repos now (for dependency `electron-to-chromium/1.5.13` - see previous comment on this PR). The IP ticket is still under review - it might be closed today or two weeks from now, no way to know. I see two options:

- add the dependency in question to the license check ignore list, in any/all repos where the failure happens
- ignore license check failures, but only if/when only this specific dependency is the cause of the failure.

WDYT?

**Review by marcdumais-work — APPROVED** [review]
LGTM - thanks for this contribution! 

The corresponding TC incubator PR is still under review but has 1 approval already, so it looks like it will be merged. The second approval for this PR here should be a TC committer, that will have the complete view on this.

There is also the matter of the failed license check workflow, for reasons unrelated to this PR, that we need to decide what to do about.

**Review by bhufmann — APPROVED** [review]
LGTM. Thanks for the contribution.

**Pull request merged**
